// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Message.proto

package com.message;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.message.MessageEnum)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.message.MessageEnum}
   */
  public static final class MessageEnum extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.message.MessageEnum)
      MessageEnumOrBuilder {
    // Use MessageEnum.newBuilder() to construct.
    private MessageEnum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageEnum(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageEnum defaultInstance;
    public static MessageEnum getDefaultInstance() {
      return defaultInstance;
    }

    public MessageEnum getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.message.Message.internal_static_com_message_MessageEnum_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.message.Message.internal_static_com_message_MessageEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.message.Message.MessageEnum.class, com.message.Message.MessageEnum.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageEnum> PARSER =
        new com.google.protobuf.AbstractParser<MessageEnum>() {
      public MessageEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageEnum(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageEnum> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.message.MessageEnum.MessageId}
     */
    public enum MessageId
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>C_Login = 10;</code>
       *
       * <pre>
       *----成对消息区
       * </pre>
       */
      C_Login(0, 10),
      /**
       * <code>S_Login = 11;</code>
       *
       * <pre>
       *登录请求返回
       * </pre>
       */
      S_Login(1, 11),
      /**
       * <code>C_ChatMsg = 100;</code>
       *
       * <pre>
       *聊天消息
       * </pre>
       */
      C_ChatMsg(2, 100),
      /**
       * <code>S_ChatMsg = 101;</code>
       *
       * <pre>
       *聊天消息
       * </pre>
       */
      S_ChatMsg(3, 101),
      /**
       * <code>C_LoginChat = 102;</code>
       *
       * <pre>
       *登录聊天室
       * </pre>
       */
      C_LoginChat(4, 102),
      /**
       * <code>S_LoginChat = 103;</code>
       *
       * <pre>
       *登录聊天室
       * </pre>
       */
      S_LoginChat(5, 103),
      /**
       * <code>S_SynHeartbeat = 1001;</code>
       *
       * <pre>
       *----仅服务器发送消息区
       * </pre>
       */
      S_SynHeartbeat(6, 1001),
      /**
       * <code>C_Heartbeat = 2000;</code>
       *
       * <pre>
       *----仅客户端发送消息区
       * </pre>
       */
      C_Heartbeat(7, 2000),
      ;

      /**
       * <code>C_Login = 10;</code>
       *
       * <pre>
       *----成对消息区
       * </pre>
       */
      public static final int C_Login_VALUE = 10;
      /**
       * <code>S_Login = 11;</code>
       *
       * <pre>
       *登录请求返回
       * </pre>
       */
      public static final int S_Login_VALUE = 11;
      /**
       * <code>C_ChatMsg = 100;</code>
       *
       * <pre>
       *聊天消息
       * </pre>
       */
      public static final int C_ChatMsg_VALUE = 100;
      /**
       * <code>S_ChatMsg = 101;</code>
       *
       * <pre>
       *聊天消息
       * </pre>
       */
      public static final int S_ChatMsg_VALUE = 101;
      /**
       * <code>C_LoginChat = 102;</code>
       *
       * <pre>
       *登录聊天室
       * </pre>
       */
      public static final int C_LoginChat_VALUE = 102;
      /**
       * <code>S_LoginChat = 103;</code>
       *
       * <pre>
       *登录聊天室
       * </pre>
       */
      public static final int S_LoginChat_VALUE = 103;
      /**
       * <code>S_SynHeartbeat = 1001;</code>
       *
       * <pre>
       *----仅服务器发送消息区
       * </pre>
       */
      public static final int S_SynHeartbeat_VALUE = 1001;
      /**
       * <code>C_Heartbeat = 2000;</code>
       *
       * <pre>
       *----仅客户端发送消息区
       * </pre>
       */
      public static final int C_Heartbeat_VALUE = 2000;


      public final int getNumber() { return value; }

      public static MessageId valueOf(int value) {
        switch (value) {
          case 10: return C_Login;
          case 11: return S_Login;
          case 100: return C_ChatMsg;
          case 101: return S_ChatMsg;
          case 102: return C_LoginChat;
          case 103: return S_LoginChat;
          case 1001: return S_SynHeartbeat;
          case 2000: return C_Heartbeat;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageId>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageId>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageId>() {
              public MessageId findValueByNumber(int number) {
                return MessageId.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.message.Message.MessageEnum.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageId[] VALUES = values();

      public static MessageId valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageId(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.message.MessageEnum.MessageId)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.message.Message.MessageEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.Message.MessageEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.Message.MessageEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.message.Message.MessageEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.message.Message.MessageEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.Message.MessageEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.message.Message.MessageEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.message.Message.MessageEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.message.Message.MessageEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.message.Message.MessageEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.message.Message.MessageEnum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.message.MessageEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.message.MessageEnum)
        com.message.Message.MessageEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.message.Message.internal_static_com_message_MessageEnum_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.message.Message.internal_static_com_message_MessageEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.message.Message.MessageEnum.class, com.message.Message.MessageEnum.Builder.class);
      }

      // Construct using com.message.Message.MessageEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.message.Message.internal_static_com_message_MessageEnum_descriptor;
      }

      public com.message.Message.MessageEnum getDefaultInstanceForType() {
        return com.message.Message.MessageEnum.getDefaultInstance();
      }

      public com.message.Message.MessageEnum build() {
        com.message.Message.MessageEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.message.Message.MessageEnum buildPartial() {
        com.message.Message.MessageEnum result = new com.message.Message.MessageEnum(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.message.Message.MessageEnum) {
          return mergeFrom((com.message.Message.MessageEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.message.Message.MessageEnum other) {
        if (other == com.message.Message.MessageEnum.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.message.Message.MessageEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.message.Message.MessageEnum) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.message.MessageEnum)
    }

    static {
      defaultInstance = new MessageEnum(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.message.MessageEnum)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_message_MessageEnum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_message_MessageEnum_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/Message.proto\022\013com.message\"\234\001\n\013M" +
      "essageEnum\"\214\001\n\tMessageId\022\013\n\007C_Login\020\n\022\013\n" +
      "\007S_Login\020\013\022\r\n\tC_ChatMsg\020d\022\r\n\tS_ChatMsg\020e" +
      "\022\017\n\013C_LoginChat\020f\022\017\n\013S_LoginChat\020g\022\023\n\016S_" +
      "SynHeartbeat\020\351\007\022\020\n\013C_Heartbeat\020\320\017"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_message_MessageEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_message_MessageEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_message_MessageEnum_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
